### ISSUE TITLE
Delay después de una etiqueta html

### ISSUE THREAD

**Issue by adecora** [JaimeObregon/iteisa.com#1]
Hola Jaime, en el loop que se utiliza para simular la escritura del div en pantalla, una vez que encuentra la primera etiqueta html y se pone el skip a true y el delay del timeout a cero, nunca vuelve a modificarse, la condición `!skip && contents[i] === ">"` y el delay sigue siendo cero para el resto del contenido del timeout (no sólo para las etiquetas html).

```javascript
const loop = () => {
        if (contents[i] === undefined) {
          clearTimeout(timeout);
          return;
        }

        if (!skip && contents[i] === ">") {
          skip = false;
          i++;
        } else if (contents[i] === "<") {
          skip = true;
          i++;
        }

        div.innerHTML = contents.slice(0, ++i);

        const milliseconds = skip ? 0 : typeDelay;
        timeout = setTimeout(loop, milliseconds);
      };
```

**Comment by JaimeObregon** [comment]
¡Hola, @adecora! Ese fragmento está comentado en el código y nunca llega a correr. Forma parte de un experimento que algún día terminaré :) pero que de momento quedó a medias.

Sea como fuere, y aunque quizá ya has dado con la solución, podría servirte algo como esto:

```JavaScript
if (skip) {
    if (contents[i] === '>') {
      skip = false
    }
    i++
  } else {
    if (contents[i] === '<') {
      skip = true
    }
    terminal.innerHTML = contents.slice(0, ++i)
  }
```

Voy a cerrar el issue porque esto quedará resuelto cuando regrese a este proyecto y lo termine y publique, pero siéntete libre de reabrirlo o comentar lo que desees. ¡Un abrazo! :)
